# Generated by Django 4.0.5 on 2022-07-12 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0002_user_score_alter_submissions_user_id_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_des',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='submissions',
            name='submitted_code',
            field=models.TimeField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='testcases',
            name='input_testcases',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='testcases',
            name='otput_testcases',
            field=models.TextField(max_length=1000),
        ),
    ]
