# Generated by Django 4.0.5 on 2022-07-13 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0003_alter_question_question_des_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissions',
            name='submission_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
